language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

php:
    - 5.4
    - 5.5
    - 5.6
    - nightly
    - hhvm

matrix:
    fast_finish: true

before_install:
    - bash -c 'wget https://scrutinizer-ci.com/ocular.phar'
    - composer self-update

install:
    - composer install

script:
    - vendor/bin/phpunit -c phpunit.xml.dist --coverage-text
    - php console psysh -V

after_script:
  - bash -c 'php ocular.phar code-coverage:upload --format=php-clover coverage.xml'

notifications:
    email: false
